### ISSUE TITLE
Airwatch Tab doesn't appear

### ISSUE THREAD

**Issue by Dolens** [pluginsGLPI/airwatch#1]
Hello,

I installed your plugin with GLPI 0.90.3 and FusionIventory 0.90+1.3. I successfully import devices from Airwatch but I can't manage to have the Airwatch tab because AirWatch devices are not imported in the plugin_airwatch_details table so the device is not recognize as an AirWatch device.

If you have any advice :)

**Comment by wawax** [comment]
Hello.
You need to apply this commit : https://github.com/fusioninventory/fusioninventory-for-glpi/commit/f982e560ada9d3971d8d16e7f402f4a455cd6954

**Comment by Dolens** [comment]
Thanks, everything is working nice now

**Comment by wawax** [comment]
Great. Please don't hesitate to send comments and feedback, the plugin is quite new!

**Comment by Dolens** [comment]
At this  time I just saw that the serial number of the device in the Computer tab is in fact the IMEI of the device. Don't know if it's the wanted behavior
